# Generated by Django 4.1.7 on 2023-05-12 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('payment_id', models.IntegerField(null=True)),
                ('stamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.IntegerField(default='unspecified', primary_key=True, serialize=False)),
                ('plane_number', models.CharField(max_length=50)),
                ('dep_airport', models.CharField(max_length=100)),
                ('des_airport', models.CharField(max_length=100)),
                ('dep_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('seatbusi_occupied', models.IntegerField()),
                ('max_seatbusi', models.IntegerField()),
                ('seatbusi_price', models.FloatField()),
                ('seatcoom_occupied', models.IntegerField()),
                ('max_seatcoom', models.IntegerField()),
                ('seatcoom_price', models.FloatField()),
                ('seatfirst_occupied', models.IntegerField()),
                ('max_seatfirst', models.IntegerField()),
                ('seatfirst_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.IntegerField(default='unspecified', primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=50)),
                ('refund_time', models.DateTimeField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='unspecified', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('seat_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.flights'),
        ),
    ]
